language: python
python:
  - 3.4
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: required
script: nosetests tests
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
notifications:
  email: false
